const commonColumns = [
  { key: "id", label: "ID", type: "text", locked: true },
  { key: "estado", label: "Estado", type: "status" },
  { key: "nombre", label: "Nombre", type: "text", primary: true },
  { key: "tipo", label: "Tipo", type: "text" },
  { key: "documento", label: "Documento", type: "text" },
  { key: "descripcion", label: "Descripción", type: "text" },
  { key: "email", label: "Email", type: "text" },
  { key: "total", label: "Total", type: "money" },
  { key: "moneda", label: "Moneda", type: "text" },
  { key: "acciones", label: "Acciones", type: "actions", locked: true },
];

const commonRows = [
  {
    id: "REG-001",
    estado: "ACTIVO",
    nombre: "Registro de ejemplo",
    tipo: "General",
    documento: "20333444556",
    descripcion: "Descripción o referencia del registro",
    email: "info@example.com",
    total: 45000,
    moneda: "ARS",
  },
  {
    id: "REG-002",
    estado: "PENDIENTE",
    nombre: "Segundo registro",
    tipo: "General",
    documento: "30711222334",
    descripcion: "Información complementaria",
    email: "admin@example.com",
    total: 100000,
    moneda: "ARS",
  },
  {
    id: "REG-003",
    estado: "INACTIVO",
    nombre: "Tercer registro",
    tipo: "Especial",
    documento: "27123456789",
    descripcion: "Observaciones internas",
    email: "contacto@example.com",
    total: 20576,
    moneda: "ARS",
  },
];

const defaultActions = {
  view: true,
  edit: true,
  delete: true,
  confirm: false,
  confirmLabel: "Confirmar",
};

function makeSection({
  key,
  group,
  title,
  subtitle,
  path,
  createPath,
  endpoint,
  columns = commonColumns,
  rows = commonRows,
  primaryFilters = ["estado", "tipo", "moneda"],
  laneField = "estado",
  actions = {},
}) {
  return {
    key,
    group,
    title,
    subtitle,
    path,
    createPath,
    endpoint,
    columns,
    rows,
    primaryFilters,
    laneField,
    actions: {
      ...defaultActions,
      ...actions,
    },
    defaultVisibleColumns: columns.map((column) => column.key),
  };
}

export const entitySections = [
  makeSection({
    key: "personas",
    group: "Estructural",
    title: "Personas",
    subtitle: "Gestión estructural de personas.",
    path: "/estructural/personas",
    createPath: "/estructural/personas/new",
    endpoint: "/api/estructural/personas",
  }),
  makeSection({
    key: "razones-sociales",
    group: "Estructural",
    title: "Razones Sociales",
    subtitle: "Gestión estructural de razones sociales.",
    path: "/estructural/razones-sociales",
    createPath: "/estructural/razones-sociales/new",
    endpoint: "/api/estructural/razones-sociales",
  }),
  makeSection({
    key: "cbus",
    group: "Estructural",
    title: "CBUs",
    subtitle: "Gestión estructural de CBUs.",
    path: "/estructural/cbus",
    createPath: "/estructural/cbus/new",
    endpoint: "/api/estructural/cbus",
  }),
  makeSection({
    key: "cuentas",
    group: "Estructural",
    title: "Cuentas",
    subtitle: "Gestión estructural de cuentas.",
    path: "/estructural/cuentas",
    createPath: "/estructural/cuentas/new",
    endpoint: "/api/estructural/cuentas",
  }),
  makeSection({
    key: "colaboradores",
    group: "Estructural",
    title: "Colaboradores",
    subtitle: "Gestión estructural de colaboradores.",
    path: "/estructural/colaboradores",
    createPath: "/estructural/colaboradores/new",
    endpoint: "/api/estructural/colaboradores",
  }),
  makeSection({
    key: "proyectos",
    group: "Estructural",
    title: "Proyectos",
    subtitle: "Gestión estructural de proyectos.",
    path: "/estructural/proyectos",
    createPath: "/estructural/proyectos/new",
    endpoint: "/api/estructural/proyectos",
  }),
  makeSection({
    key: "recurrentes",
    group: "Estructural",
    title: "Recurrentes",
    subtitle: "Gestión estructural de recurrentes.",
    path: "/estructural/recurrentes",
    createPath: "/estructural/recurrentes/new",
    endpoint: "/api/estructural/recurrentes",
  }),
  makeSection({
    key: "facturacion",
    group: "Estructural",
    title: "Facturación",
    subtitle: "Gestión estructural de facturación.",
    path: "/estructural/facturacion",
    createPath: "/estructural/facturacion/new",
    endpoint: "/api/estructural/facturacion",
  }),

  makeSection({
    key: "tiempo",
    group: "Proveedores",
    title: "Tiempo",
    subtitle: "Gestión de tiempo de proveedores.",
    path: "/proveedores/tiempo",
    createPath: "/proveedores/tiempo/new",
    endpoint: "/api/proveedores/tiempo",
  }),

  makeSection({
    key: "agenda",
    group: "Gestión",
    title: "Agenda",
    subtitle: "Gestión de agenda.",
    path: "/gestion/agenda",
    createPath: "/gestion/agenda/new",
    endpoint: "/api/gestion/agenda",
  }),
  makeSection({
    key: "activos",
    group: "Gestión",
    title: "Activos",
    subtitle: "Gestión de activos.",
    path: "/gestion/activos",
    createPath: "/gestion/activos/new",
    endpoint: "/api/gestion/activos",
  }),
  makeSection({
    key: "dominios",
    group: "Gestión",
    title: "Dominios",
    subtitle: "Gestión de dominios.",
    path: "/gestion/dominios",
    createPath: "/gestion/dominios/new",
    endpoint: "/api/gestion/dominios",
  }),

  makeSection({
    key: "reportes-ventas",
    group: "Reportes",
    title: "Ventas",
    subtitle: "Reporte de ventas.",
    path: "/reportes/ventas",
    createPath: null,
    endpoint: "/api/reportes/ventas",
  }),
  makeSection({
    key: "recurrentes-por-cuentas",
    group: "Reportes",
    title: "Recurrentes por cuentas",
    subtitle: "Reporte de recurrentes por cuentas.",
    path: "/reportes/recurrentes-por-cuentas",
    createPath: null,
    endpoint: "/api/reportes/recurrentes-por-cuentas",
  }),
  makeSection({
    key: "recurrentes-por-actividades",
    group: "Reportes",
    title: "Recurrentes por actividades",
    subtitle: "Reporte de recurrentes por actividades.",
    path: "/reportes/recurrentes-por-actividades",
    createPath: null,
    endpoint: "/api/reportes/recurrentes-por-actividades",
  }),

  makeSection({
    key: "administracion-comercial-ventas",
    group: "Administración y Comercial",
    title: "Ventas",
    subtitle: "Administración comercial de ventas.",
    path: "/administracion-comercial/ventas",
    createPath: null,
    endpoint: "/api/administracion-comercial/ventas",
  }),
  makeSection({
    key: "indices",
    group: "Administración y Comercial",
    title: "Índices",
    subtitle: "Administración comercial de índices.",
    path: "/administracion-comercial/indices",
    createPath: null,
    endpoint: "/api/administracion-comercial/indices",
  }),
];

export function getEntitySectionByKey(key) {
  return entitySections.find((section) => section.key === key);
}

export function getEntitySectionsByGroup(group) {
  return entitySections.filter((section) => section.group === group);
}
