const commonColumns = [
  { key: "id", label: "ID", type: "text", locked: true },
  { key: "estado", label: "Estado", type: "status" },
  { key: "nombre", label: "Nombre", type: "text", primary: true },
  { key: "tipo", label: "Tipo", type: "text" },
  { key: "documento", label: "Documento", type: "text" },
  { key: "descripcion", label: "Descripción", type: "text" },
  { key: "email", label: "Email", type: "text" },
  { key: "total", label: "Total", type: "money" },
  { key: "moneda", label: "Moneda", type: "text" },
  { key: "acciones", label: "Acciones", type: "actions", locked: true },
];

const commonRows = [
  {
    id: "REG-001",
    estado: "ACTIVO",
    nombre: "Registro de ejemplo",
    tipo: "General",
    documento: "20333444556",
    descripcion: "Descripción o referencia del registro",
    email: "info@example.com",
    total: 45000,
    moneda: "ARS",
  },
  {
    id: "REG-002",
    estado: "PENDIENTE",
    nombre: "Segundo registro",
    tipo: "General",
    documento: "30711222334",
    descripcion: "Información complementaria",
    email: "admin@example.com",
    total: 100000,
    moneda: "ARS",
  },
  {
    id: "REG-003",
    estado: "INACTIVO",
    nombre: "Tercer registro",
    tipo: "Especial",
    documento: "27123456789",
    descripcion: "Observaciones internas",
    email: "contacto@example.com",
    total: 20576,
    moneda: "ARS",
  },
];

const ordenesFacturacionColumns = [
  { key: "orderId", label: "Order ID", type: "text", locked: true },
  { key: "fecha", label: "Fecha", type: "date" },
  { key: "estado", label: "Estado", type: "status" },
  { key: "tc", label: "T/C", type: "text" },
  { key: "provincia", label: "Provincia", type: "text" },
  { key: "documento", label: "Documento", type: "text" },
  { key: "razonSocial", label: "Razón Social", type: "text", primary: true },
  { key: "tipo", label: "Tipo", type: "text" },
  { key: "leyenda", label: "Leyenda", type: "text" },
  { key: "importeNeto", label: "Importe Neto", type: "number" },
  { key: "porcentajeIva", label: "%", type: "number" },
  { key: "iva", label: "Iva", type: "number" },
  { key: "importeTotal", label: "Importe Total", type: "money" },
  { key: "moneda", label: "Moneda", type: "text" },
  { key: "emisora", label: "Emisora", type: "text" },
  { key: "emails", label: "Emails", type: "text" },
  { key: "acciones", label: "Acciones", type: "actions", locked: true },
];

const ordenesFacturacionRows = [
  {
    orderId: "2111",
    fecha: "01/06/2026",
    estado: "ESPERANDO PAGO",
    tc: "C",
    provincia: "CABA",
    documento: "23148603464",
    razonSocial: "CUK INGRID LILIAN",
    tipo: "Consumidor Final",
    leyenda: "Honorarios profesionales Junio 2026",
    importeNeto: 20576,
    porcentajeIva: 0,
    iva: 0,
    importeTotal: 20576,
    moneda: "ARS",
    emisora: "CALABRESE LUCIANO JAVIER",
    emails: "info@ingridcuk.com.ar",
  },
  {
    orderId: "2112",
    fecha: "01/06/2026",
    estado: "PAGADO",
    tc: "A",
    provincia: "Buenos Aires",
    documento: "30711222334",
    razonSocial: "EJEMPLO S.A.",
    tipo: "Responsable Inscripto",
    leyenda: "Servicios profesionales Junio 2026",
    importeNeto: 100000,
    porcentajeIva: 21,
    iva: 21000,
    importeTotal: 121000,
    moneda: "ARS",
    emisora: "CALABRESE LUCIANO JAVIER",
    emails: "administracion@ejemplo.com",
  },
  {
    orderId: "2113",
    fecha: "02/06/2026",
    estado: "BORRADOR",
    tc: "B",
    provincia: "Córdoba",
    documento: "20333444556",
    razonSocial: "JUAN PEREZ",
    tipo: "Monotributista",
    leyenda: "Abono mensual Junio 2026",
    importeNeto: 45000,
    porcentajeIva: 0,
    iva: 0,
    importeTotal: 45000,
    moneda: "ARS",
    emisora: "CALABRESE LUCIANO JAVIER",
    emails: "juan.perez@example.com",
  },
  {
    orderId: "2114",
    fecha: "03/06/2026",
    estado: "ANULADO",
    tc: "C",
    provincia: "Santa Fe",
    documento: "20222111222",
    razonSocial: "CLIENTE ANULADO",
    tipo: "Consumidor Final",
    leyenda: "Comprobante anulado",
    importeNeto: 30000,
    porcentajeIva: 0,
    iva: 0,
    importeTotal: 30000,
    moneda: "ARS",
    emisora: "CALABRESE LUCIANO JAVIER",
    emails: "cliente@example.com",
  },
];

const tasksColumns = [
  { key: "id", label: "Task", type: "text", locked: true },
  { key: "tipo", label: "Tipo", type: "badge" },
  { key: "titulo", label: "Título", type: "text", primary: true },
  { key: "estado", label: "Estado", type: "status" },
  { key: "prioridad", label: "Prioridad", type: "badge" },
  { key: "acciones", label: "Acciones", type: "actions", locked: true },
];

const tasksRows = [
  {
    id: "TASK-8782",
    tipo: "Documentation",
    titulo: "You can't compress the program without quantifying the open-source S...",
    estado: "In Progress",
    prioridad: "Medium",
  },
  {
    id: "TASK-7878",
    tipo: "Documentation",
    titulo: "Try to calculate the EXE feed, maybe it will index the multi-byte pixel!",
    estado: "Backlog",
    prioridad: "Medium",
  },
  {
    id: "TASK-7839",
    tipo: "Bug",
    titulo: "We need to bypass the neural TCP card!",
    estado: "Todo",
    prioridad: "High",
  },
  {
    id: "TASK-5562",
    tipo: "Feature",
    titulo: "The SAS interface is down, bypass the open-source pixel so we can bac...",
    estado: "Backlog",
    prioridad: "Medium",
  },
  {
    id: "TASK-8686",
    tipo: "Feature",
    titulo: "I'll parse the wireless SSL protocol, that should driver the API panel!",
    estado: "Canceled",
    prioridad: "Medium",
  },
  {
    id: "TASK-1280",
    tipo: "Bug",
    titulo: "Use the digital TLS panel, then you can transmit the haptic system!",
    estado: "Done",
    prioridad: "High",
  },
  {
    id: "TASK-7262",
    tipo: "Feature",
    titulo: "The UTF8 application is down, parse the neural bandwidth so we can ba...",
    estado: "Done",
    prioridad: "High",
  },
  {
    id: "TASK-1138",
    tipo: "Feature",
    titulo: "Generating the driver won't do anything, we need to quantify the 1080p ...",
    estado: "In Progress",
    prioridad: "Medium",
  },
  {
    id: "TASK-7184",
    tipo: "Feature",
    titulo: "We need to program the back-end THX pixel!",
    estado: "Todo",
    prioridad: "Low",
  },
  {
    id: "TASK-5160",
    tipo: "Documentation",
    titulo: "Calculating the bus won't do anything, we need to navigate the back-en...",
    estado: "In Progress",
    prioridad: "High",
  },
];

const usersColumns = [
  { key: "id", label: "ID", type: "text", locked: true },
  {
    key: "name",
    label: "Name",
    type: "text",
    primary: true,
    cellLayout: "stacked",
  },
  { key: "email", label: "Email", type: "text" },
  { key: "username", label: "Username", type: "text" },
  { key: "status", label: "Status", type: "status" },
  { key: "role", label: "Role", type: "badge" },
  { key: "acciones", label: "Actions", type: "actions", locked: true },
];

const defaultBadgeStyles = {
  estado: {
    ACTIVO: "green",
    PENDIENTE: "blue",
    INACTIVO: "red",
    BORRADOR: "yellow",
  },
};

const ordenesFacturacionBadgeStyles = {
  estado: {
    "ESPERANDO PAGO": "blue",
    PAGADO: "green",
    BORRADOR: "yellow",
    ANULADO: "red",
  },
};

const tasksBadgeStyles = {
  estado: {
    "In Progress": "blue",
    Backlog: "slate",
    Todo: "slate",
    Canceled: "red",
    Done: "green",
  },
  tipo: {
    Documentation: "blue",
    Bug: "red",
    Feature: "yellow",
  },
  prioridad: {
    High: "red",
    Medium: "blue",
    Low: "slate",
  },
};

const usersBadgeStyles = {
  status: {
    Pending: "yellow",
    Approved: "green",
    Suspended: "red",
  },
  role: {
    admin: "blue",
    user: "slate",
    Superadmin: "blue",
    Admin: "blue",
    Manager: "yellow",
    Cashier: "slate",
  },
};

const defaultActions = {
  view: true,
  edit: true,
  delete: true,
  confirm: false,
  confirmLabel: "Confirmar",
};



function makeSection({
  key,
  group,
  title,
  subtitle,
  path,
  createPath,
  endpoint,
  tableName,
  mapperKey,
  dataSource,
  actionsKey,
  statsKey,
  emptyMessage,
  columns,
  rows,
  primaryFilters,
  laneField,
  badgeStyles,
  actions = {},
}) {
  const hasRemoteDataSource = Boolean(endpoint || tableName || dataSource);
  const resolvedRows = rows ?? (hasRemoteDataSource ? [] : commonRows);
  const resolvedColumns = columns ?? (hasRemoteDataSource ? [] : commonColumns);

  return {
    key,
    group,
    title,
    subtitle,
    path,
    createPath,
    endpoint,
    tableName,
    mapperKey,
    dataSource,
    actionsKey,
    statsKey,
    emptyMessage,
    columns: resolvedColumns,
    rows: resolvedRows,
    primaryFilters,
    laneField,
    badgeStyles: badgeStyles || defaultBadgeStyles,
    actions: {
      ...defaultActions,
      ...actions,
    },
    defaultVisibleColumns: resolvedColumns.map((column) => column.key),
  };
}

export const entitySections = [
  makeSection({
    key: "personas",
    group: "Estructural",
    title: "Personas",
    subtitle: "Gestión estructural de personas.",
    path: "/estructural/personas",
    createPath: "/estructural/personas/new",
    tableName: "users",
    mapperKey: "authUsers",
    columns: usersColumns,
    primaryFilters: ["status", "role"],
    laneField: "status",
    badgeStyles: usersBadgeStyles,
  }),
  makeSection({
    key: "razones-sociales",
    group: "Estructural",
    title: "Razones Sociales",
    subtitle: "Gestión estructural de razones sociales.",
    path: "/estructural/razones-sociales",
    createPath: "/estructural/razones-sociales/new",
    endpoint: "/api/estructural/razones-sociales",
  }),
  makeSection({
    key: "cbus",
    group: "Estructural",
    title: "CBUs",
    subtitle: "Gestión estructural de CBUs.",
    path: "/estructural/cbus",
    createPath: "/estructural/cbus/new",
    endpoint: "/api/estructural/cbus",
  }),
  makeSection({
    key: "cuentas",
    group: "Estructural",
    title: "Cuentas",
    subtitle: "Gestión estructural de cuentas.",
    path: "/estructural/cuentas",
    createPath: "/estructural/cuentas/new",
    endpoint: "/api/estructural/cuentas",
  }),
  makeSection({
    key: "colaboradores",
    group: "Estructural",
    title: "Colaboradores",
    subtitle: "Gestión estructural de colaboradores.",
    path: "/estructural/colaboradores",
    createPath: "/estructural/colaboradores/new",
    endpoint: "/api/estructural/colaboradores",
  }),
  makeSection({
    key: "proyectos",
    group: "Estructural",
    title: "Proyectos",
    subtitle: "Gestión estructural de proyectos.",
    path: "/estructural/proyectos",
    createPath: "/estructural/proyectos/new",
    endpoint: "/api/estructural/proyectos",
  }),
  makeSection({
    key: "recurrentes",
    group: "Estructural",
    title: "Recurrentes",
    subtitle: "Gestión estructural de recurrentes.",
    path: "/estructural/recurrentes",
    createPath: "/estructural/recurrentes/new",
    endpoint: "/api/estructural/recurrentes",
  }),
  makeSection({
    key: "facturacion",
    group: "Estructural",
    title: "Facturación",
    subtitle: "Gestión estructural de facturación.",
    path: "/estructural/facturacion",
    createPath: "/estructural/facturacion/new",
    endpoint: "/api/estructural/facturacion",
  }),

  makeSection({
    key: "tiempo",
    group: "Proveedores",
    title: "Tiempo",
    subtitle: "Gestión de tiempo de proveedores.",
    path: "/proveedores/tiempo",
    createPath: "/proveedores/tiempo/new",
    endpoint: "/api/proveedores/tiempo",
  }),

  makeSection({
    key: "agenda",
    group: "Gestión",
    title: "Agenda",
    subtitle: "Gestión de agenda.",
    path: "/gestion/agenda",
    createPath: "/gestion/agenda/new",
    endpoint: "/api/gestion/agenda",
  }),
  makeSection({
    key: "activos",
    group: "Gestión",
    title: "Activos",
    subtitle: "Gestión de activos.",
    path: "/gestion/activos",
    createPath: "/gestion/activos/new",
    endpoint: "/api/gestion/activos",
  }),
  makeSection({
    key: "dominios",
    group: "Gestión",
    title: "Dominios",
    subtitle: "Gestión de dominios.",
    path: "/gestion/dominios",
    createPath: "/gestion/dominios/new",
    endpoint: "/api/gestion/dominios",
  }),

  makeSection({
    key: "reportes-ventas",
    group: "Reportes",
    title: "Ventas",
    subtitle: "Reporte de ventas.",
    path: "/reportes/ventas",
    createPath: "/reportes/ventas/new",
    endpoint: "/api/reportes/ventas",
  }),
  makeSection({
    key: "recurrentes-por-cuentas",
    group: "Reportes",
    title: "Recurrentes por cuentas",
    subtitle: "Reporte de recurrentes por cuentas.",
    path: "/reportes/recurrentes-por-cuentas",
    createPath: "/reportes/recurrentes-por-cuentas/new",
    endpoint: "/api/reportes/recurrentes-por-cuentas",
  }),
  makeSection({
    key: "recurrentes-por-actividades",
    group: "Reportes",
    title: "Recurrentes por actividades",
    subtitle: "Reporte de recurrentes por actividades.",
    path: "/reportes/recurrentes-por-actividades",
    createPath: "/reportes/recurrentes-por-actividades/new",
    endpoint: "/api/reportes/recurrentes-por-actividades",
  }),

  makeSection({
    key: "administracion-comercial-ventas",
    group: "Administración y Comercial",
    title: "Ventas",
    subtitle: "Administración comercial de ventas.",
    path: "/administracion-comercial/ventas",
    createPath: "/administracion-comercial/ventas/new",
    endpoint: "/api/administracion-comercial/ventas",
  }),
  makeSection({
    key: "indices",
    group: "Administración y Comercial",
    title: "Índices",
    subtitle: "Administración comercial de índices.",
    path: "/administracion-comercial/indices",
    createPath: "/administracion-comercial/indices/new",
    endpoint: "/api/administracion-comercial/indices",
  }),
makeSection({
  key: "ordenes-facturacion",
  group: "Administración y Comercial",
  title: "Órdenes de Facturación",
  subtitle: "Seguimiento de órdenes emitidas, estado de pago y datos fiscales.",
  path: "/administracion-comercial/ordenes-facturacion",
  createPath: "/administracion-comercial/ordenes-facturacion/new",
  tableName: "ordenes_facturacion",
  laneField: "estado_id",
})

  makeSection({
  key: "configuracion-users",
  group: "Configuración",
  title: "User List",
  subtitle: "Gestión de usuarios del sistema.",
  path: "/configuracion/users",
  createPath: "/configuracion/users/new",
  dataSource: "authUsers",
  actionsKey: "users",
  statsKey: "users",
  emptyMessage: "No hay usuarios para mostrar.",
  columns: usersColumns,
  primaryFilters: ["status", "role"],
  laneField: "status",
  badgeStyles: usersBadgeStyles,
}),

  makeSection({
    key: "configuracion-tasks",
    group: "Configuración",
    title: "Tasks",
    subtitle: "Listado de tareas configuradas.",
    path: "/configuracion/tasks",
    createPath: "/configuracion/tasks/new",
    endpoint: "/api/configuracion/tasks",
    columns: tasksColumns,
    rows: tasksRows,
    primaryFilters: ["estado", "prioridad", "tipo"],
    laneField: "estado",
    badgeStyles: tasksBadgeStyles,
  }),
];

export function getEntitySectionByKey(key) {
  return entitySections.find((section) => section.key === key);
}

export function getEntitySectionsByGroup(group) {
  return entitySections.filter((section) => section.group === group);
}