import { useEntityTable } from "@/hooks/useEntityTable";
import React, { useState, useMemo, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Check, ChevronRight, Save } from "lucide-react";
import { Card } from "@/components/ui/card";
import PageBreadcrumb from "@/components/PageBreadcrumb";

const NON_FORM_COLUMN_KEYS = new Set([
  "acciones",
  "actions",
  "select",
  "_select",
  "checkbox",
  "_checkbox",
]);

function getRowIdKey(section) {
  const columns = section.columns || [];

  if (columns.some((column) => column.key === "id")) return "id";
  if (columns.some((column) => column.key === "orderId")) return "orderId";

  return null;
}

function shouldHideColumn(column) {
  if (!column) return true;
  if (column.formHidden) return true;
  if (column.type === "actions") return true;
  if (column.type === "checkbox") return true;
  if (NON_FORM_COLUMN_KEYS.has(column.key)) return true;

  return false;
}

function isAutoGeneratedColumn(column, section) {
  const rowIdKey = getRowIdKey(section);

  if (column.formDisabled) return true;
  if (column.autoGenerated) return true;
  if (rowIdKey && column.key === rowIdKey) return true;

  return false;
}

function getUniqueValues(rows, key) {
  return Array.from(
    new Set(
      (rows || [])
        .map((row) => row?.[key])
        .filter((value) => value !== null && value !== undefined && value !== "")
        .map(String)
    )
  );
}

function getOptionsFromSection(section, column) {
  if (column.lookup) {
    const lookupMap = section.lookupMaps?.[column.key] || {};

    return Object.entries(lookupMap).map(([value, label]) => ({
      value,
      label: String(label),
    }));
  }

  if (Array.isArray(column.formOptions)) {
    return column.formOptions.map((option) =>
      typeof option === "string" ? { value: option, label: option } : option
    );
  }

  if (Array.isArray(column.options)) {
    return column.options.map((option) =>
      typeof option === "string" ? { value: option, label: option } : option
    );
  }

  const sectionFormOptions = section.formOptions?.[column.key];

  if (Array.isArray(sectionFormOptions)) {
    return sectionFormOptions.map((option) =>
      typeof option === "string" ? { value: option, label: option } : option
    );
  }

  const badgeOptions = section.badgeStyles?.[column.key];

  if (badgeOptions && typeof badgeOptions === "object") {
    return Object.keys(badgeOptions).map((value) => ({
      value,
      label: value,
    }));
  }

  const primaryFilter = (section.primaryFilters || []).find((filter) => {
    if (typeof filter === "string") return filter === column.key;
    return filter?.key === column.key;
  });

  if (primaryFilter && typeof primaryFilter === "object" && Array.isArray(primaryFilter.options)) {
    return primaryFilter.options
      .filter((option) => option.value !== "custom")
      .map((option) => ({
        value: option.value,
        label: option.label || option.value,
      }));
  }

  const rowValues = getUniqueValues(section.rows || [], column.key);

  if (
    column.type === "status" ||
    column.type === "badge" ||
    column.formType === "select" ||
    column.formType === "combobox"
  ) {
    return rowValues.map((value) => ({
      value,
      label: value,
    }));
  }

  if (["estado", "tipo", "moneda", "tc", "provincia", "emisora"].includes(column.key)) {
    return rowValues.map((value) => ({
      value,
      label: value,
    }));
  }

  return [];
}

function getFormType(section, column) {
  if (column.formType) return column.formType;

  if (column.lookup) return "select";

  const options = getOptionsFromSection(section, column);

  if (options.length > 0) return "select";

  if (column.type === "date") return "date";
  if (column.type === "number") return "number";
  if (column.type === "money") return "number";
  if (column.type === "status") return "select";
  if (column.type === "badge") return "select";

  if (column.key === "email" || column.key === "emails") return "email";
  if (column.key === "descripcion" || column.key === "leyenda") return "textarea";

  return "text";
}

function getInitialValue(section, column) {
  if (column.defaultValue !== undefined) return column.defaultValue;

  if (isAutoGeneratedColumn(column, section)) {
    return "";
  }

  const options = getOptionsFromSection(section, column);

  if (options.length > 0) {
    return options[0]?.value || "";
  }

  return "";
}

function getInputMode(column, formType) {
  if (formType === "number") return "decimal";
  if (column.key === "documento") return "numeric";

  return undefined;
}

function getPlaceholder(section, column, formType) {
  if (column.formPlaceholder) return column.formPlaceholder;

  if (isAutoGeneratedColumn(column, section)) {
    return "Se genera automáticamente";
  }

  if (formType === "select") return `Seleccionar ${column.label.toLowerCase()}`;
  if (formType === "date") return "Seleccionar fecha";
  if (formType === "number") return "0";

  return `Ingresar ${column.label.toLowerCase()}`;
}

function buildFormColumns(section) {
  return (section.columns || []).filter((column) => !shouldHideColumn(column));
}

function FormSelect({ value, onChange, options, placeholder, disabled = false }) {
  const [open, setOpen] = useState(false);
  const selectedOption = options.find((option) => String(option.value) === String(value));
  const label = selectedOption?.label || placeholder;

  return (
    <div className="relative">
      <button
        type="button"
        disabled={disabled}
        onClick={() => setOpen((current) => !current)}
        className={`inline-flex h-10 w-full items-center justify-between gap-3 rounded-xl border border-input bg-background px-4 text-sm font-medium shadow-sm transition-colors focus:outline-none focus:ring-1 focus:ring-ring/30 ${
          disabled
            ? "cursor-not-allowed bg-muted/40 text-muted-foreground opacity-80"
            : "hover:bg-muted/40"
        }`}
      >
        <span className="truncate">{label}</span>
        <ChevronRight
          className={`size-4 shrink-0 text-muted-foreground transition-transform ${
            open ? "rotate-90" : ""
          }`}
        />
      </button>

      {open && !disabled && (
        <>
          <button
            type="button"
            className="fixed inset-0 z-20 cursor-default"
            onClick={() => setOpen(false)}
            tabIndex={-1}
            aria-label="Cerrar menú"
          />

          <div className="absolute left-0 top-full z-30 mt-1.5 w-full min-w-[230px] overflow-hidden rounded-xl border border-border bg-popover p-1 shadow-lg">
            {options.map((option) => {
              const active = String(option.value) === String(value);

              return (
                <button
                  key={String(option.value)}
                  type="button"
                  onClick={() => {
                    onChange(option.value);
                    setOpen(false);
                  }}
                  className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm text-foreground transition-colors hover:bg-muted/70"
                >
                  <span className="truncate">{option.label}</span>
                  <span className="flex size-4 items-center justify-center">
                    {active && <Check className="size-4 stroke-[2]" />}
                  </span>
                </button>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}

function FormField({ section, column, value, onChange }) {
  const formType = getFormType(section, column);
  const disabled = isAutoGeneratedColumn(column, section);
  const options = getOptionsFromSection(section, column);
  const placeholder = getPlaceholder(section, column, formType);

  return (
    <div className={formType === "textarea" ? "space-y-1.5 md:col-span-2" : "space-y-1.5"}>
      <label className="text-sm font-medium">
        {column.label}
        {column.required && <span className="text-destructive"> *</span>}
      </label>

      {formType === "select" ? (
        <FormSelect
          value={value}
          onChange={onChange}
          options={options}
          placeholder={placeholder}
          disabled={disabled}
        />
      ) : formType === "textarea" ? (
        <textarea
          rows={4}
          value={value}
          disabled={disabled}
          placeholder={placeholder}
          onChange={(event) => onChange(event.target.value)}
          className={`w-full rounded-xl border border-input bg-background px-4 py-2.5 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring/30 resize-none ${
            disabled ? "cursor-not-allowed bg-muted/40 text-muted-foreground opacity-80" : ""
          }`}
        />
      ) : (
        <input
          type={formType}
          value={value}
          disabled={disabled}
          placeholder={placeholder}
          inputMode={getInputMode(column, formType)}
          step={column.type === "money" || column.type === "number" ? "any" : undefined}
          onChange={(event) => onChange(event.target.value)}
          className={`h-10 w-full rounded-xl border border-input bg-background px-4 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring/30 ${
            disabled ? "cursor-not-allowed bg-muted/40 text-muted-foreground opacity-80" : ""
          }`}
        />
      )}

      {disabled && (
        <p className="text-xs text-muted-foreground">
          Este campo se completa automáticamente.
        </p>
      )}

      {column.formHelp && (
        <p className="text-xs text-muted-foreground">
          {column.formHelp}
        </p>
      )}
    </div>
  );
}

export default function EntityCreatePage({ section }) {
  const navigate = useNavigate();

  const { section: runtimeSection } = useEntityTable(section);
  const currentSection = runtimeSection || section;

  const formColumns = useMemo(
    () => buildFormColumns(currentSection),
    [currentSection]
  );

  const initialValues = useMemo(() => {
    return Object.fromEntries(
      formColumns.map((column) => [
        column.key,
        getInitialValue(currentSection, column),
      ])
    );
  }, [formColumns, currentSection]);

  const [values, setValues] = useState(initialValues);

  useEffect(() => {
    setValues((current) => {
      const nextValues = { ...current };

      formColumns.forEach((column) => {
        if (nextValues[column.key] === undefined) {
          nextValues[column.key] = getInitialValue(currentSection, column);
        }
      });

      return nextValues;
    });
  }, [formColumns, currentSection]);

  const updateValue = (columnKey, nextValue) => {
    setValues((current) => ({
      ...current,
      [columnKey]: nextValue,
    }));
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    const payload = Object.fromEntries(
      formColumns
        .filter((column) => !isAutoGeneratedColumn(column, currentSection))
        .map((column) => [column.key, values[column.key]])
    );

    console.log("Crear registro", {
      section: currentSection.key,
      endpoint: currentSection.endpoint,
      tableName: currentSection.tableName,
      payload,
    });
  };

  return (
    <div className="space-y-6 max-w-5xl">
      <div>
        <div className="mb-2">
          <PageBreadcrumb section={currentSection} currentLabel="Agregar" />
        </div>

        <div className="flex items-center justify-between gap-4 flex-wrap">
          <div>
            <h1 className="text-2xl font-bold">Agregar {currentSection.title}</h1>
            <p className="text-sm text-muted-foreground">
              Cargá los datos principales de {currentSection.title.toLowerCase()}.
            </p>
          </div>

          <button
            type="button"
            onClick={() => navigate(currentSection.path)}
            className="inline-flex items-center gap-2 px-3 py-1.5 text-sm border border-border rounded-md hover:bg-muted"
          >
            <ArrowLeft className="size-4" />
            Volver
          </button>
        </div>
      </div>

      <form onSubmit={handleSubmit}>
        <Card className="shadow-none p-5 space-y-5">
          <div className="grid gap-4 md:grid-cols-2">
            {formColumns.map((column) => (
              <FormField
                key={column.key}
                section={currentSection}
                column={column}
                value={values[column.key] ?? ""}
                onChange={(nextValue) => updateValue(column.key, nextValue)}
              />
            ))}
          </div>

          <div className="flex justify-end border-t border-border pt-5">
            <button
              type="submit"
              className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-foreground px-4 text-sm font-medium text-background transition-opacity hover:opacity-90"
            >
              <Save className="size-4" />
              Guardar
            </button>
          </div>
        </Card>
      </form>
    </div>
  );
}