import { useEntityTable } from "@/hooks/useEntityTable";
import { createEntityRow } from "@/lib/entity-service";
import React, { useState, useMemo, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Check, ChevronRight, Save } from "lucide-react";
import { Card } from "@/components/ui/card";
import PageBreadcrumb from "@/components/PageBreadcrumb";

const NON_FORM_COLUMN_KEYS = new Set([
  "acciones",
  "actions",
  "select",
  "_select",
  "checkbox",
  "_checkbox",
]);

function getRowIdKey(section) {
  const columns = section.columns || [];

  if (columns.some((column) => column.key === "id")) return "id";
  if (columns.some((column) => column.key === "orderId")) return "orderId";

  return null;
}

function shouldHideColumn(column) {
  if (!column) return true;
  if (column.formHidden) return true;
  if (column.virtual) return true;
  if (column.type === "actions") return true;
  if (column.type === "checkbox") return true;
  if (NON_FORM_COLUMN_KEYS.has(column.key)) return true;

  return false;
}

function isAutoGeneratedColumn(column, section) {
  const rowIdKey = getRowIdKey(section);

  if (column.formDisabled) return true;
  if (column.autoGenerated) return true;
  if (rowIdKey && column.key === rowIdKey) return true;

  return false;
}

function getUniqueValues(rows, key) {
  return Array.from(
    new Set(
      (rows || [])
        .map((row) => row?.[key])
        .filter((value) => value !== null && value !== undefined && value !== "")
        .map(String)
    )
  );
}

function getOptionsFromSection(section, column) {
  if (column.lookup) {
    const lookupMap = section.lookupMaps?.[column.key] || {};

    return Object.entries(lookupMap).map(([value, label]) => ({
      value,
      label: String(label),
    }));
  }

  if (Array.isArray(column.formOptions)) {
    return column.formOptions.map((option) =>
      typeof option === "string" ? { value: option, label: option } : option
    );
  }

  if (Array.isArray(column.options)) {
    return column.options.map((option) =>
      typeof option === "string" ? { value: option, label: option } : option
    );
  }

  const sectionFormOptions = section.formOptions?.[column.key];

  if (Array.isArray(sectionFormOptions)) {
    return sectionFormOptions.map((option) =>
      typeof option === "string" ? { value: option, label: option } : option
    );
  }

  const badgeOptions = section.badgeStyles?.[column.key];

  if (badgeOptions && typeof badgeOptions === "object") {
    return Object.keys(badgeOptions).map((value) => ({
      value,
      label: value,
    }));
  }

if (column.type !== "date" && column.formType !== "date") {
  const primaryFilter = (section.primaryFilters || []).find((filter) => {
    if (typeof filter === "string") return filter === column.key;
    return filter?.key === column.key;
  });

  if (primaryFilter && typeof primaryFilter === "object" && Array.isArray(primaryFilter.options)) {
    return primaryFilter.options
      .filter((option) => option.value !== "custom")
      .map((option) => ({
        value: option.value,
        label: option.label || option.value,
      }));
  }
}

  const rowValues = getUniqueValues(section.rows || [], column.key);

  if (
    column.type === "status" ||
    column.type === "badge" ||
    column.formType === "select" ||
    column.formType === "combobox"
  ) {
    return rowValues.map((value) => ({
      value,
      label: value,
    }));
  }

  if (["estado", "tipo", "moneda", "tc", "provincia", "emisora"].includes(column.key)) {
    return rowValues.map((value) => ({
      value,
      label: value,
    }));
  }

  return [];
}

function getFormType(section, column) {
  if (column.formType) return column.formType;

  if (column.lookup) return "select";

  const options = getOptionsFromSection(section, column);

  if (options.length > 0) return "select";

  if (column.type === "date") return "date";
  if (column.type === "number") return "number";
  if (column.type === "money") return "number";
  if (column.type === "status") return "select";
  if (column.type === "badge") return "select";

  if (column.key === "email" || column.key === "emails") return "email";
  if (column.key === "descripcion" || column.key === "leyenda") return "textarea";

  return "text";
}

function getInitialValue(section, column) {
  if (column.defaultValue !== undefined) return column.defaultValue;

  if (isAutoGeneratedColumn(column, section)) {
    return "";
  }

  const options = getOptionsFromSection(section, column);

  if (options.length > 0) {
    return options[0]?.value || "";
  }

  return "";
}

function getInputMode(column, formType) {
  if (formType === "number") return "decimal";
  if (column.key === "documento") return "numeric";

  return undefined;
}

function getPlaceholder(section, column, formType) {
  if (column.formPlaceholder) return column.formPlaceholder;

  if (isAutoGeneratedColumn(column, section)) {
    return "Se genera automáticamente";
  }

  if (formType === "select") return `Seleccionar ${column.label.toLowerCase()}`;
  if (formType === "date") return "Seleccionar fecha";
  if (formType === "number") return "0";

  return `Ingresar ${column.label.toLowerCase()}`;
}

function buildFormColumns(section) {
  const baseColumns = (section.columns || []).filter((column) => !shouldHideColumn(column));

  const extraColumns = (section.formExtraColumns || []).filter(
    (column) =>
      column.key &&
      !baseColumns.some((baseColumn) => baseColumn.key === column.key)
  );

  return [...baseColumns, ...extraColumns];
}

function FormSelect({ value, onChange, options, placeholder, disabled = false }) {
  const [open, setOpen] = useState(false);
  const selectedOption = options.find((option) => String(option.value) === String(value));
  const label = selectedOption?.label || placeholder;

  return (
    <div className="relative">
      <button
        type="button"
        disabled={disabled}
        onClick={() => setOpen((current) => !current)}
        className={`inline-flex h-10 w-full items-center justify-between gap-3 rounded-xl border border-input bg-background px-4 text-sm font-medium shadow-sm transition-colors focus:outline-none focus:ring-1 focus:ring-ring/30 ${
          disabled
            ? "cursor-not-allowed bg-muted/40 text-muted-foreground opacity-80"
            : "hover:bg-muted/40"
        }`}
      >
        <span className="truncate">{label}</span>
        <ChevronRight
          className={`size-4 shrink-0 text-muted-foreground transition-transform ${
            open ? "rotate-90" : ""
          }`}
        />
      </button>

      {open && !disabled && (
        <>
          <button
            type="button"
            className="fixed inset-0 z-20 cursor-default"
            onClick={() => setOpen(false)}
            tabIndex={-1}
            aria-label="Cerrar menú"
          />

          <div className="absolute left-0 top-full z-30 mt-1.5 w-full min-w-[230px] overflow-hidden rounded-xl border border-border bg-popover p-1 shadow-lg">
            {options.map((option) => {
              const active = String(option.value) === String(value);

              return (
                <button
                  key={String(option.value)}
                  type="button"
                  onClick={() => {
                    onChange(option.value);
                    setOpen(false);
                  }}
                  className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm text-foreground transition-colors hover:bg-muted/70"
                >
                  <span className="truncate">{option.label}</span>
                  <span className="flex size-4 items-center justify-center">
                    {active && <Check className="size-4 stroke-[2]" />}
                  </span>
                </button>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}

function formatDateLabel(value) {
  if (!value) return "";

  const [year, month, day] = String(value).split("-").map(Number);

  if (!year || !month || !day) return value;

  return `${String(day).padStart(2, "0")}/${String(month).padStart(2, "0")}/${year}`;
}

function getMonthLabel(date) {
  return date.toLocaleDateString("en-US", {
    month: "long",
    year: "numeric",
  });
}

function toDateInputValue(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

function DatePickerInput({ value, onChange, disabled = false, placeholder = "dd/mm/aaaa" }) {
  const [open, setOpen] = useState(false);
  const selectedDate = value ? new Date(`${value}T00:00:00`) : null;
  const [viewDate, setViewDate] = useState(selectedDate || new Date());

  useEffect(() => {
    if (value) {
      setViewDate(new Date(`${value}T00:00:00`));
    }
  }, [value]);

  const year = viewDate.getFullYear();
  const month = viewDate.getMonth();

  const firstDayOfMonth = new Date(year, month, 1);
  const firstVisibleDate = new Date(firstDayOfMonth);
  firstVisibleDate.setDate(firstVisibleDate.getDate() - firstVisibleDate.getDay());

  const days = Array.from({ length: 42 }, (_, index) => {
    const date = new Date(firstVisibleDate);
    date.setDate(firstVisibleDate.getDate() + index);
    return date;
  });

  const selectedValue = selectedDate ? toDateInputValue(selectedDate) : "";

  const goToPreviousMonth = () => {
    setViewDate((current) => new Date(current.getFullYear(), current.getMonth() - 1, 1));
  };

  const goToNextMonth = () => {
    setViewDate((current) => new Date(current.getFullYear(), current.getMonth() + 1, 1));
  };

  const handleSelectDate = (date) => {
    onChange(toDateInputValue(date));
    setOpen(false);
  };

  return (
    <div className="relative">
      <button
        type="button"
        disabled={disabled}
        onClick={() => setOpen((current) => !current)}
        className={`inline-flex h-10 w-full items-center justify-between rounded-xl border border-input bg-background px-4 text-sm shadow-sm transition-colors focus:outline-none focus:ring-1 focus:ring-ring/30 ${
          disabled
            ? "cursor-not-allowed bg-muted/40 text-muted-foreground opacity-80"
            : "hover:bg-muted/40"
        }`}
      >
        <span className={value ? "text-foreground" : "text-muted-foreground"}>
          {value ? formatDateLabel(value) : placeholder}
        </span>

        <svg
          viewBox="0 0 24 24"
          className="size-4 text-muted-foreground"
          fill="none"
          stroke="currentColor"
          strokeWidth="1.8"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <rect x="3" y="4" width="18" height="18" rx="2" />
          <path d="M16 2v4" />
          <path d="M8 2v4" />
          <path d="M3 10h18" />
        </svg>
      </button>

      {open && !disabled && (
        <>
          <button
            type="button"
            className="fixed inset-0 z-20 cursor-default"
            onClick={() => setOpen(false)}
            tabIndex={-1}
            aria-label="Cerrar calendario"
          />

          <div className="absolute left-0 top-full z-30 mt-2 w-[340px] rounded-xl border border-border bg-popover p-6 text-popover-foreground shadow-xl">
            <div className="mb-7 flex items-center justify-between">
              <button
                type="button"
                onClick={goToPreviousMonth}
                className="inline-flex size-8 items-center justify-center rounded-full text-foreground hover:bg-muted"
                aria-label="Mes anterior"
              >
                ‹
              </button>

              <div className="text-lg font-semibold">
                {getMonthLabel(viewDate)}
              </div>

              <button
                type="button"
                onClick={goToNextMonth}
                className="inline-flex size-8 items-center justify-center rounded-full text-foreground hover:bg-muted"
                aria-label="Mes siguiente"
              >
                ›
              </button>
            </div>

            <div className="mb-3 grid grid-cols-7 gap-2 text-center text-sm font-medium text-muted-foreground">
              {["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"].map((day) => (
                <div key={day}>{day}</div>
              ))}
            </div>

            <div className="grid grid-cols-7 gap-2 text-center">
              {days.map((date) => {
                const dateValue = toDateInputValue(date);
                const isCurrentMonth = date.getMonth() === month;
                const isSelected = dateValue === selectedValue;

                return (
                  <button
                    key={dateValue}
                    type="button"
                    onClick={() => handleSelectDate(date)}
                    className={`inline-flex size-9 items-center justify-center rounded-xl text-base transition-colors ${
                      isSelected
                        ? "bg-muted text-foreground font-semibold"
                        : isCurrentMonth
                          ? "text-foreground hover:bg-muted"
                          : "text-muted-foreground/30 hover:bg-muted/40"
                    }`}
                  >
                    {date.getDate()}
                  </button>
                );
              })}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function FormField({ section, column, value, onChange }) {
  const formType = getFormType(section, column);
  const disabled = isAutoGeneratedColumn(column, section);
  const options = getOptionsFromSection(section, column);
  const placeholder = getPlaceholder(section, column, formType);

  return (
    <div className={formType === "textarea" ? "space-y-1.5 md:col-span-2" : "space-y-1.5"}>
      <label className="text-sm font-medium">
        {column.label}
        {column.required && <span className="text-destructive"> *</span>}
      </label>

{formType === "select" ? (
  <FormSelect
    value={value}
    onChange={onChange}
    options={options}
    placeholder={placeholder}
    disabled={disabled}
  />
) : formType === "date" ? (
  <DatePickerInput
    value={value}
    onChange={onChange}
    disabled={disabled}
    placeholder="dd/mm/aaaa"
  />
) : formType === "textarea" ? (
        <textarea
          rows={4}
          value={value}
          disabled={disabled}
          placeholder={placeholder}
          onChange={(event) => onChange(event.target.value)}
          className={`w-full rounded-xl border border-input bg-background px-4 py-2.5 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring/30 resize-none ${
            disabled ? "cursor-not-allowed bg-muted/40 text-muted-foreground opacity-80" : ""
          }`}
        />
      ) : (
        <input
          type={formType}
          value={value}
          disabled={disabled}
          placeholder={placeholder}
          inputMode={getInputMode(column, formType)}
          step={column.type === "money" || column.type === "number" ? "any" : undefined}
          onChange={(event) => onChange(event.target.value)}
          className={`h-10 w-full rounded-xl border border-input bg-background px-4 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring/30 ${
            disabled ? "cursor-not-allowed bg-muted/40 text-muted-foreground opacity-80" : ""
          }`}
        />
      )}

      {disabled && (
        <p className="text-xs text-muted-foreground">
          Este campo se completa automáticamente.
        </p>
      )}

      {column.formHelp && (
        <p className="text-xs text-muted-foreground">
          {column.formHelp}
        </p>
      )}
    </div>
  );
}

function parseDateForStorage(value) {
  if (!value) return null;

  const [year, month, day] = String(value).split("-").map(Number);

  if (!year || !month || !day) {
    return value;
  }

  const date = new Date(year, month - 1, day);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return Math.floor(date.getTime() / 1000);
}

function isIvaPercentageColumn(column) {
  return column?.key === "iva_porcentaje";
}

function normalizeIvaPercentageForStorage(value) {
  if (value === "" || value === null || value === undefined) return null;

  const numberValue = Number(String(value).replace(",", "."));

  if (Number.isNaN(numberValue)) return value;

  return 1 + numberValue / 100;
}

function normalizeFormValue(column, value) {
  if (value === "" || value === undefined) {
    return null;
  }

  if (column.lookup) {
    const numericValue = Number(value);
    return Number.isNaN(numericValue) ? value : numericValue;
  }

  if (column.formType === "date" || column.type === "date") {
    return parseDateForStorage(value);
  }

  if (isIvaPercentageColumn(column)) {
    return normalizeIvaPercentageForStorage(value);
  }

  if (column.formType === "number" || column.type === "number" || column.type === "money") {
    const numericValue = Number(value);
    return Number.isNaN(numericValue) ? value : numericValue;
  }

  return value;
}

export default function EntityCreatePage({ section }) {
  const navigate = useNavigate();

  const { section: runtimeSection } = useEntityTable(section);
  const currentSection = runtimeSection || section;

  const formColumns = useMemo(
    () => buildFormColumns(currentSection),
    [currentSection]
  );

  const initialValues = useMemo(() => {
    return Object.fromEntries(
      formColumns.map((column) => [
        column.key,
        getInitialValue(currentSection, column),
      ])
    );
  }, [formColumns, currentSection]);

  const [values, setValues] = useState(initialValues);

  useEffect(() => {
    setValues((current) => {
      const nextValues = { ...current };

      formColumns.forEach((column) => {
        if (nextValues[column.key] === undefined) {
          nextValues[column.key] = getInitialValue(currentSection, column);
        }
      });

      return nextValues;
    });
  }, [formColumns, currentSection]);

  const updateValue = (columnKey, nextValue) => {
    setValues((current) => ({
      ...current,
      [columnKey]: nextValue,
    }));
  };

const handleSubmit = async (event) => {
  event.preventDefault();

  if (!currentSection.tableName) {
    console.error("No hay tableName configurado para crear el registro.", currentSection);
    return;
  }

  const payload = Object.fromEntries(
    formColumns
      .filter((column) => !isAutoGeneratedColumn(column, currentSection))
      .filter((column) => !shouldHideColumn(column))
      .map((column) => [
        column.key,
        normalizeFormValue(column, values[column.key]),
      ])
  );

  await createEntityRow(currentSection.tableName, payload);

  if (typeof currentSection.onRefresh === "function") {
    await currentSection.onRefresh();
  }

  navigate(currentSection.path);
};

  return (
    <div className="space-y-6 max-w-5xl">
      <div>
        <div className="mb-2">
          <PageBreadcrumb section={currentSection} currentLabel="Agregar" />
        </div>

        <div className="flex items-center justify-between gap-4 flex-wrap">
          <div>
            <h1 className="text-2xl font-bold">Agregar {currentSection.title}</h1>
            <p className="text-sm text-muted-foreground">
              Cargá los datos principales de {currentSection.title.toLowerCase()}.
            </p>
          </div>

          <button
            type="button"
            onClick={() => navigate(currentSection.path)}
            className="inline-flex items-center gap-2 px-3 py-1.5 text-sm border border-border rounded-md hover:bg-muted"
          >
            <ArrowLeft className="size-4" />
            Volver
          </button>
        </div>
      </div>

      <form onSubmit={handleSubmit}>
        <Card className="shadow-none p-5 space-y-5">
          <div className="grid gap-4 md:grid-cols-2">
            {formColumns.map((column) => (
              <FormField
                key={column.key}
                section={currentSection}
                column={column}
                value={values[column.key] ?? ""}
                onChange={(nextValue) => updateValue(column.key, nextValue)}
              />
            ))}
          </div>

          <div className="flex justify-end border-t border-border pt-5">
            <button
              type="submit"
              className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-foreground px-4 text-sm font-medium text-background transition-opacity hover:opacity-90"
            >
              <Save className="size-4" />
              Guardar
            </button>
          </div>
        </Card>
      </form>
    </div>
  );
}